//
//  TipsData.swift
//  Trashure
//
//  Created by Gus Adi on 26/10/20.
//

import Foundation
import UIKit

struct TipsData {
    let data = [TipsModel(tipsImage: UIImage(named: "tongSampah")!, title: "Cara memilah sampah yang baik", isi: "Cara memilah sampah yang baik, hal yang pertama harus kamu lakuin adalah dengan cara mengetahui jenis-jenis sampah tersebut, mulai dari sampah kering, sampah basah. Sampah kering biasa nya terdiri dari sampah botol-botolan, kaleng-kalengan bekas minuman biasanya, sampah basah bisanya bekas sisa-sisa makanan. \n\nUntuk memilahnya, kami sarankan untuk mengelompokkannya menjadi dua kelompok, yang pertama sampah kering yang kedua sampah basah, disarankan untuk menyetor sampah kering saja, agar mudah ditimbang dan dihitung beratnya. \n\nJika anda mempunyai kardus, saran kami untuk memilah sampah kering tersebut menjadi beberapa kategori lagi, yang pertama sampah botol, yang kedua sampah kaleng dan yang terakhir adalah sampah kardus. Setelah itu masukkan sampah yang kalian pungut kedalam kardus-kardus yang sudah disediakan berdasarkan kategori yang sudah dibuat.", date: "17 April 2019"),
        TipsModel(tipsImage: UIImage(named: "trashbagImage")!, title: "Cara menggunakan Trashbag ID", isi: "Cara memilah sampah yang baik, hal yang pertama harus kamu lakuin adalah dengan cara mengetahui jenis-jenis sampah tersebut, mulai dari sampah kering, sampah basah. Sampah kering biasa nya terdiri dari sampah botol-botolan, kaleng-kalengan bekas minuman biasanya, sampah basah bisanya bekas sisa-sisa makanan. /n/nUntuk memilahnya, kami sarankan untuk mengelompokkannya menjadi dua kelompok, yang pertama sampah kering yang kedua sampah basah, disarankan untuk menyetor sampah kering saja, agar mudah ditimbang dan dihitung beratnya. /n/nJika anda mempunyai kardus, saran kami untuk memilah sampah kering tersebut menjadi beberapa kategori lagi, yang pertama sampah botol, yang kedua sampah kaleng dan yang terakhir adalah sampah kardus. Setelah itu masukkan sampah yang kalian pungut kedalam kardus-kardus yang sudah disediakan berdasarkan kategori yang sudah dibuat.", date: "09 April 2019"),
        TipsModel(tipsImage: UIImage(named: "fotoBuangSampah"), title: "Cara membuang sampah mantan", isi: "Cara memilah sampah yang baik, hal yang pertama harus kamu lakuin adalah dengan cara mengetahui jenis-jenis sampah tersebut, mulai dari sampah kering, sampah basah. Sampah kering biasa nya terdiri dari sampah botol-botolan, kaleng-kalengan bekas minuman biasanya, sampah basah bisanya bekas sisa-sisa makanan. Untuk memilahnya, kami sarankan untuk mengelompokkannya menjadi dua kelompok, yang pertama sampah kering yang kedua sampah basah, disarankan untuk menyetor sampah kering saja, agar mudah ditimbang dan dihitung beratnya. Jika anda mempunyai kardus, saran kami untuk memilah sampah kering tersebut menjadi beberapa kategori lagi, yang pertama sampah botol, yang kedua sampah kaleng dan yang terakhir adalah sampah kardus. Setelah itu masukkan sampah yang kalian pungut kedalam kardus-kardus yang sudah disediakan berdasarkan kategori yang sudah dibuat.", date: "27 Maret 2019")]
}
